version: "3"

services:
  mongo_db:
    container_name: database
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  server:
    build: ./server
    container_name: server
    image: numer_server_image
    ports:
      - 3000:3000
    environment:
      SERVER_PORT: 3000
      MONGO_URL: mongodb://mongo_db:27017/Numerical
      DOMAIN: http://localhost:3000
    depends_on:
      - mongo_db

  client:
    build: ./client
    container_name: client
    image: numer_client_image
    ports:
      - 5173:5173
    environment:
      END_POINT: http://localhost:3000
    depends_on:
      - server

volumes:
  mongo_db: {}
