openapi: 3.0.0
info:
  title: UKB-PROFILES
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /auth/register:
    post:
      summary: Returns a l  ist of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON OBJECT with the user's information.
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                    example: John Doe
                  password:
                    type: string
                    example: test123
