name: Deploy
on:
  push:
    braches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Client
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create ,env file
        run: |
          echo "END_POINT=https://numer-api.unknowkubbrother.net" >> .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: unknowkubbrother/numerical:latest