name: Deploy
on:
  push:
    braches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Server
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create ,env file
        run: |
          echo "SERVER_PORT=3000" >> .env
          echo "MONGO_URL=${{secrets.MONGO_URL}} >> .env
          echo "DOMAIN=https://numer-api.unknowkubbrother.net>> .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: unknowkubbrother/numerical-server:latest